version: '3.8'

services:
  scancerai:
    build:
      context: .
      dockerfile: Dockerfile
    image: scancerai:latest
    container_name: scancerai-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add any other environment variables your app needs
      # - API_URL=https://api.example.com
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G 