version: '3.8'

services:
  scancerai:
    build:
      context: .
      dockerfile: Dockerfile
    image: scancerai:latest
    restart: unless-stopped
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - NEXT_SHARP_PATH=/tmp/node_modules/sharp
      - PORT=3000
      - NEXT_PUBLIC_APP_URL=http://scancerai-compose-txtzkk-037383-5-223-50-174.traefik.me
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scancerai.rule=Host(`scancerai-compose-txtzkk-037383-5-223-50-174.traefik.me`)"
      - "traefik.http.services.scancerai.loadbalancer.server.port=3000"
      - "traefik.http.routers.scancerai.entrypoints=web"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s 