services:
  scancerai:
    build:
      context: .
      dockerfile: Dockerfile
    image: scancerai:latest
    container_name: scancerai-app
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-3001}:3000"
    environment:
      - NODE_ENV=production
      # Add any other environment variables your app needs
      # - API_URL=https://api.example.com
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G 